// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: media/v1/media.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2018 Sagittarius LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Sagittarius_Media_V1_Info {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Resource id of the media. It must have the format of "media/*/info".
  /// For example: "media/1111-2222-3333-4444/info".
  public var mediaHash: String = String()

  public var tracks: [Sagittarius_Media_V1_Info.TrackInfo] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct TrackInfo {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var types: Sagittarius_Media_V1_Info.TrackInfo.TypeEnum = .video

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum TypeEnum: SwiftProtobuf.Enum {
      public typealias RawValue = Int
      case video // = 0
      case audio // = 1
      case text // = 2
      case other // = 3
      case UNRECOGNIZED(Int)

      public init() {
        self = .video
      }

      public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .video
        case 1: self = .audio
        case 2: self = .text
        case 3: self = .other
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      public var rawValue: Int {
        switch self {
        case .video: return 0
        case .audio: return 1
        case .text: return 2
        case .other: return 3
        case .UNRECOGNIZED(let i): return i
        }
      }

    }

    public init() {}
  }

  public init() {}
}

#if swift(>=4.2)

extension Sagittarius_Media_V1_Info.TrackInfo.TypeEnum: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Sagittarius_Media_V1_Info.TrackInfo.TypeEnum] = [
    .video,
    .audio,
    .text,
    .other,
  ]
}

#endif  // swift(>=4.2)

/// retrieve media info like sound track resolutions, length/duringation etc.
public struct Sagittarius_Media_V1_GetInfoRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// quick hash of the media. For example: "media/1111-2222-3333-4444/info".
  public var mediaHash: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// try to update media info
public struct Sagittarius_Media_V1_UpdateInfoRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// quick hash of the media. For example: "media/1111-2222-3333-4444/info".
  public var mediaHash: String = String()

  /// the media info to be updated
  public var info: Sagittarius_Media_V1_Info {
    get {return _info ?? Sagittarius_Media_V1_Info()}
    set {_info = newValue}
  }
  /// Returns true if `info` has been explicitly set.
  public var hasInfo: Bool {return self._info != nil}
  /// Clears the value of `info`. Subsequent reads from it will return its default value.
  public mutating func clearInfo() {self._info = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _info: Sagittarius_Media_V1_Info? = nil
}

/// try to retrieve Thumbnails
public struct Sagittarius_Media_V1_ThumbnailTimeRangesRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// use quick media hash to get thumbnails
  public var mediaHash: String = String()

  /// time length of the  media resource, in seconds
  public var mediaLength: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// time range is used to tell the client the screenshot range
public struct Sagittarius_Media_V1_TimeRange {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// the beginning of the time range, in seconds
  public var begin: Double = 0

  /// the end of the time range, in seconds
  public var end: Double = 0

  /// time interval between each thumbnails, in seconds
  public var interval: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Sagittarius_Media_V1_ThumbnailTimeRangesResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var error: Google_Rpc_Status {
    get {return _error ?? Google_Rpc_Status()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {return self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  /// time range is used to tell the client the screenshot range
  public var mediaHash: String = String()

  /// thumbnails that the server have, in time ranges
  public var availables: [Sagittarius_Media_V1_TimeRange] = []

  /// thumbnails that the server is missing and wanted, in time ranges
  public var missings: [Sagittarius_Media_V1_TimeRange] = []

  /// access token for read and/or write thumbnail by timestamp
  /// session_token will not have write premission if there is not missing
  public var token: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: Google_Rpc_Status? = nil
}

public struct Sagittarius_Media_V1_ThumbnailRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mediaHash: String = String()

  /// which thumbnail the client wants
  public var time: Sagittarius_Media_V1_ThumbnailRequest.OneOf_Time? = nil

  public var range: Sagittarius_Media_V1_TimeRange {
    get {
      if case .range(let v)? = time {return v}
      return Sagittarius_Media_V1_TimeRange()
    }
    set {time = .range(newValue)}
  }

  public var timestamp: Double {
    get {
      if case .timestamp(let v)? = time {return v}
      return 0
    }
    set {time = .timestamp(newValue)}
  }

  /// access token for read and write thumbnail by timestamp
  public var token: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// which thumbnail the client wants
  public enum OneOf_Time: Equatable {
    case range(Sagittarius_Media_V1_TimeRange)
    case timestamp(Double)

  #if !swift(>=4.1)
    public static func ==(lhs: Sagittarius_Media_V1_ThumbnailRequest.OneOf_Time, rhs: Sagittarius_Media_V1_ThumbnailRequest.OneOf_Time) -> Bool {
      switch (lhs, rhs) {
      case (.range(let l), .range(let r)): return l == r
      case (.timestamp(let l), .timestamp(let r)): return l == r
      default: return false
      }
    }
  #endif
  }

  public init() {}
}

public struct Sagittarius_Media_V1_Thumbnail {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// timestamp of this thumbnail in relative to the begginning of the media_hash
  public var timestamp: Double = 0

  /// image's file extension
  public var ext: String = String()

  /// image's binary content
  public var payload: Data = SwiftProtobuf.Internal.emptyData

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Sagittarius_Media_V1_ThumbnailResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var error: Google_Rpc_Status {
    get {return _error ?? Google_Rpc_Status()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {return self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  /// thumbnails. with timestamp, extension, and payload
  public var thumbnails: [Sagittarius_Media_V1_Thumbnail] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: Google_Rpc_Status? = nil
}

public struct Sagittarius_Media_V1_UpdateThumbnailRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mediaHash: String = String()

  /// the thumbnails to be updated
  public var thumbnails: [Sagittarius_Media_V1_Thumbnail] = []

  /// access token for read and write thumbnail by timestamp
  public var token: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sagittarius.media.v1"

extension Sagittarius_Media_V1_Info: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Info"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "media_hash"),
    2: .same(proto: "tracks"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.mediaHash)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.tracks)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mediaHash.isEmpty {
      try visitor.visitSingularStringField(value: self.mediaHash, fieldNumber: 1)
    }
    if !self.tracks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tracks, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Sagittarius_Media_V1_Info, rhs: Sagittarius_Media_V1_Info) -> Bool {
    if lhs.mediaHash != rhs.mediaHash {return false}
    if lhs.tracks != rhs.tracks {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sagittarius_Media_V1_Info.TrackInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Sagittarius_Media_V1_Info.protoMessageName + ".TrackInfo"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "types"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularEnumField(value: &self.types)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.types != .video {
      try visitor.visitSingularEnumField(value: self.types, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Sagittarius_Media_V1_Info.TrackInfo, rhs: Sagittarius_Media_V1_Info.TrackInfo) -> Bool {
    if lhs.types != rhs.types {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sagittarius_Media_V1_Info.TrackInfo.TypeEnum: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "VIDEO"),
    1: .same(proto: "AUDIO"),
    2: .same(proto: "TEXT"),
    3: .same(proto: "OTHER"),
  ]
}

extension Sagittarius_Media_V1_GetInfoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetInfoRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "media_hash"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.mediaHash)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mediaHash.isEmpty {
      try visitor.visitSingularStringField(value: self.mediaHash, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Sagittarius_Media_V1_GetInfoRequest, rhs: Sagittarius_Media_V1_GetInfoRequest) -> Bool {
    if lhs.mediaHash != rhs.mediaHash {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sagittarius_Media_V1_UpdateInfoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateInfoRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "media_hash"),
    2: .same(proto: "info"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.mediaHash)
      case 2: try decoder.decodeSingularMessageField(value: &self._info)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mediaHash.isEmpty {
      try visitor.visitSingularStringField(value: self.mediaHash, fieldNumber: 1)
    }
    if let v = self._info {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Sagittarius_Media_V1_UpdateInfoRequest, rhs: Sagittarius_Media_V1_UpdateInfoRequest) -> Bool {
    if lhs.mediaHash != rhs.mediaHash {return false}
    if lhs._info != rhs._info {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sagittarius_Media_V1_ThumbnailTimeRangesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ThumbnailTimeRangesRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "media_hash"),
    2: .standard(proto: "media_length"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.mediaHash)
      case 2: try decoder.decodeSingularDoubleField(value: &self.mediaLength)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mediaHash.isEmpty {
      try visitor.visitSingularStringField(value: self.mediaHash, fieldNumber: 1)
    }
    if self.mediaLength != 0 {
      try visitor.visitSingularDoubleField(value: self.mediaLength, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Sagittarius_Media_V1_ThumbnailTimeRangesRequest, rhs: Sagittarius_Media_V1_ThumbnailTimeRangesRequest) -> Bool {
    if lhs.mediaHash != rhs.mediaHash {return false}
    if lhs.mediaLength != rhs.mediaLength {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sagittarius_Media_V1_TimeRange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TimeRange"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "begin"),
    2: .same(proto: "end"),
    3: .same(proto: "interval"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularDoubleField(value: &self.begin)
      case 2: try decoder.decodeSingularDoubleField(value: &self.end)
      case 3: try decoder.decodeSingularDoubleField(value: &self.interval)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.begin != 0 {
      try visitor.visitSingularDoubleField(value: self.begin, fieldNumber: 1)
    }
    if self.end != 0 {
      try visitor.visitSingularDoubleField(value: self.end, fieldNumber: 2)
    }
    if self.interval != 0 {
      try visitor.visitSingularDoubleField(value: self.interval, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Sagittarius_Media_V1_TimeRange, rhs: Sagittarius_Media_V1_TimeRange) -> Bool {
    if lhs.begin != rhs.begin {return false}
    if lhs.end != rhs.end {return false}
    if lhs.interval != rhs.interval {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sagittarius_Media_V1_ThumbnailTimeRangesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ThumbnailTimeRangesResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "error"),
    2: .standard(proto: "media_hash"),
    3: .same(proto: "availables"),
    4: .same(proto: "missings"),
    5: .same(proto: "token"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._error)
      case 2: try decoder.decodeSingularStringField(value: &self.mediaHash)
      case 3: try decoder.decodeRepeatedMessageField(value: &self.availables)
      case 4: try decoder.decodeRepeatedMessageField(value: &self.missings)
      case 5: try decoder.decodeSingularStringField(value: &self.token)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.mediaHash.isEmpty {
      try visitor.visitSingularStringField(value: self.mediaHash, fieldNumber: 2)
    }
    if !self.availables.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.availables, fieldNumber: 3)
    }
    if !self.missings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.missings, fieldNumber: 4)
    }
    if !self.token.isEmpty {
      try visitor.visitSingularStringField(value: self.token, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Sagittarius_Media_V1_ThumbnailTimeRangesResponse, rhs: Sagittarius_Media_V1_ThumbnailTimeRangesResponse) -> Bool {
    if lhs._error != rhs._error {return false}
    if lhs.mediaHash != rhs.mediaHash {return false}
    if lhs.availables != rhs.availables {return false}
    if lhs.missings != rhs.missings {return false}
    if lhs.token != rhs.token {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sagittarius_Media_V1_ThumbnailRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ThumbnailRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "media_hash"),
    2: .same(proto: "range"),
    3: .same(proto: "timestamp"),
    4: .same(proto: "token"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.mediaHash)
      case 2:
        var v: Sagittarius_Media_V1_TimeRange?
        if let current = self.time {
          try decoder.handleConflictingOneOf()
          if case .range(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {self.time = .range(v)}
      case 3:
        if self.time != nil {try decoder.handleConflictingOneOf()}
        var v: Double?
        try decoder.decodeSingularDoubleField(value: &v)
        if let v = v {self.time = .timestamp(v)}
      case 4: try decoder.decodeSingularStringField(value: &self.token)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mediaHash.isEmpty {
      try visitor.visitSingularStringField(value: self.mediaHash, fieldNumber: 1)
    }
    switch self.time {
    case .range(let v)?:
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    case .timestamp(let v)?:
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 3)
    case nil: break
    }
    if !self.token.isEmpty {
      try visitor.visitSingularStringField(value: self.token, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Sagittarius_Media_V1_ThumbnailRequest, rhs: Sagittarius_Media_V1_ThumbnailRequest) -> Bool {
    if lhs.mediaHash != rhs.mediaHash {return false}
    if lhs.time != rhs.time {return false}
    if lhs.token != rhs.token {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sagittarius_Media_V1_Thumbnail: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Thumbnail"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "timestamp"),
    2: .same(proto: "ext"),
    3: .same(proto: "payload"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularDoubleField(value: &self.timestamp)
      case 2: try decoder.decodeSingularStringField(value: &self.ext)
      case 3: try decoder.decodeSingularBytesField(value: &self.payload)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.timestamp != 0 {
      try visitor.visitSingularDoubleField(value: self.timestamp, fieldNumber: 1)
    }
    if !self.ext.isEmpty {
      try visitor.visitSingularStringField(value: self.ext, fieldNumber: 2)
    }
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Sagittarius_Media_V1_Thumbnail, rhs: Sagittarius_Media_V1_Thumbnail) -> Bool {
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.ext != rhs.ext {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sagittarius_Media_V1_ThumbnailResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ThumbnailResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "error"),
    2: .same(proto: "thumbnails"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._error)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.thumbnails)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.thumbnails.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.thumbnails, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Sagittarius_Media_V1_ThumbnailResponse, rhs: Sagittarius_Media_V1_ThumbnailResponse) -> Bool {
    if lhs._error != rhs._error {return false}
    if lhs.thumbnails != rhs.thumbnails {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sagittarius_Media_V1_UpdateThumbnailRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateThumbnailRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "media_hash"),
    2: .same(proto: "thumbnails"),
    3: .same(proto: "token"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.mediaHash)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.thumbnails)
      case 3: try decoder.decodeSingularStringField(value: &self.token)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mediaHash.isEmpty {
      try visitor.visitSingularStringField(value: self.mediaHash, fieldNumber: 1)
    }
    if !self.thumbnails.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.thumbnails, fieldNumber: 2)
    }
    if !self.token.isEmpty {
      try visitor.visitSingularStringField(value: self.token, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Sagittarius_Media_V1_UpdateThumbnailRequest, rhs: Sagittarius_Media_V1_UpdateThumbnailRequest) -> Bool {
    if lhs.mediaHash != rhs.mediaHash {return false}
    if lhs.thumbnails != rhs.thumbnails {return false}
    if lhs.token != rhs.token {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
